apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: a9s-redis-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: a9s-redis-demo
        tier: frontend
    spec:
      containers:
      - name: a9s-redis-demo
        image: mycluster.icp:8500/a9s-ds/a9s-redis-demo:latest
        ports:
        - containerPort: 9090
        env:
        - name: "REDIS_HOST"
          valueFrom:
            secretKeyRef:
              name: redis-binding
              key: host
        - name: "REDIS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: redis-binding
              key: password
        - name: "REDIS_PORT"
          valueFrom:
            secretKeyRef:
              name: redis-binding
              key: port
